language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov

notifications:
  email: false
  slack: nbakaev:ogljTlQvuQMCZ5Ti9UdRi7iU
    on_success: always
    on_failure: always