language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
notifications:
  email: false
  slack: nbakaev:ogljTlQvuQMCZ5Ti9UdRi7iU
deploy:
  provider: bintray
  file: ".bintray"
  user: nbakaev
  key:
    secure: M/p/oCITIHIcxThoyzF4yyLqR0UCGG323+wrmjGX4crFyml1dtWAu8y/92HXxPT+eQiLAw8gAmflDs3DXZTAW/T7intA80NMCpi+7sVgRS6/8BTVe6JAMY4FWTJ+pF0scDTndX4VRzC4BAOuhp+WHG1jA9b5EOQ6eRiJSfFJWxzJ+XQLn3hLnyxbdSwnW03zf+OrGo42/hxVfvUKizyxLqEAZWpvtq3GcN7XbcmfpOrG4NWVnI6FF+RzbZE9Hut98iNScfGWPTidkZ7AUnVlvFbFY3JM7D5Zc5fxtbNvlkNQa8l08tmpTHicVlPwPQHG1coqMJejGPEUB1PpRtfX0NpvRApfXrMdqoCvwL0pCGUu4zWoPL+gtCENj0kzowrsDm8PxSadUVbLcOvxkoi0BZE3txvxgKkXGMW24N5UKXbW+GEItKwhueGG1qsy79nyfL5+RnWCuxB5Qy67rT/BFqlnFDLJDX6TxHVa8oOsfhjo1dVhfgF/phgP8zVkaEKY9fdi6jpRfd03iY8fL9hIdJ3bmnTg637HMfUs9zn1qMlOA0xWG/OOv3DkfLC/q6SrcyaV4Oz40nNbKS5yv3KKUxirf7jeIEHSOcIBRTLLUscTKORTpMakl2fD8vBkrMdYNmCyb8M+luBsoG/+i4ZUBnebqpxXZkT5nWqvwKK2esQ=
