language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
notifications:
  email: false
  slack: nbakaev:ogljTlQvuQMCZ5Ti9UdRi7iU
env:
  global:
   - secure: lgssR0+cvrerrofLDd02C2tH0Ws2i6FNuohwJG34NnfLqWp0g6UYqF/BHV936SrKKGBhSKHKMKSMfQV1S1D1IJ4SHocb+EAPTDFzboeHd9NEc+ZHpB5cC1jKHJ8pAie2LhuvoFNc3hZZeEzIsu1ldQU1gV5IAbE0sP3u8rGI1U9wydVT3KXAH1FtgkrO5GVxcy3GtZF3nMeLaWEU+I2d78CVcoqoRVZvQ0pkU2BXcmqU6jV4sfvr5ENJTeQrh/fCKgmDRSmgTfV2XfuwYmoslZuaXVSrncioK70DvGp7jgwzhqGKQUCp2u2SonDWFMfXz3k781FysyFBhm7hMEnSKbvSSIG7OlZHlrZ0L5NwMOBGB9ww2fYU0innZHi3Yn1ubxSpbdvZvm/uDpuX8JFIhCENoxDft4GG8TuQ1Arq1sHIZQFaqXq/8b0CyE7+ihvbDCAuEMW3WzZcUa8/VP0s/wp9pJryES1uc5zLWV4/tsgd5g6IrRZagnPosEP6LXtIOETuw7XLMdtoJcx2qTpv4kGS9xdGTEBx84wDHvkce2AWqydNoPcGp6UDye+6vIzDxTlSwIeXuEQp5EI7vw+G07VocCifemjOeu7bMkUyv9TUUp87FpdxYk/IDEW3ZXa0BV/zPxKkDpUwxFeUTUj2v8qDYEwiHRcaFAu7rsQpb8c=
   - BASE_DIR="`pwd`"
after_success:
- "$BASE_DIR/deploy/publish.sh"
cache:
  directories:
  - "$HOME/.m2"