apiVersion: v1
kind: ReplicationController
metadata:
  name: hishop-api-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: hishop-api
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: hishop-api
    spec:
      containers:
      - name: hishop-api
        image: nbakaev/hishop
        imagePullPolicy: Always
        restartPolicy: Always
        ports:
        - containerPort: 8080
        dnsPolicy: ClusterFirst
